on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Make Release

jobs:
  build:
    name: Make Release
    runs-on: ubuntu-latest
    steps:
      - name: Install arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '9-2019-q4' # The arm-none-eabi-gcc release to use.

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd firmware
          make all TOOLCHAIN_PATH=""

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          files: |
            ./firmware/builds/Wunderkiste/Wunderkiste.hex
            ./firmware/builds/Wunderkiste/Wunderkiste.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}